#
# ./manage start 172.16.10.29 "LEDGER_INSTANCE_NAME=My Iamza-sandbox" WEB_SERVER_HOST_PORT=9000
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-issuer-agent-configmap
  namespace: address-issuer
data:
  # Server Variables
  ACAPY_ADMIN_INSECURE_MODE: "true"
  ACAPY_AUTO_PROVISION: "true"
  ACAPY_DEBUG_CONNECTIONS: "true"
  ACAPY_ENDPOINT: "https://addrissuer-agent.iamza-sandbox.com"
  ACAPY_LABEL: "Physical Address Issuer"
  ACAPY_GENESIS_URL: "https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_demonet_genesis"
  # ACAPY_GENESIS_URL: "https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis"
  ACAPY_WALLET_NAME: "addrissuer_wallet"
  #  ACAPY_WALLET_KEY: ""
  ACAPY_WALLET_TYPE: "indy"
  ACAPY_WALLET_STORAGE_TYPE: postgres_storage
  ACAPY_WALLET_STORAGE_CONFIG: '{"url":"postgres-nodeport-svc.postgres.svc.cluster.local:5432","wallet_scheme":"DatabasePerWallet"}'
  #  ACAPY_WALLET_STORAGE_CREDS: ''
  ACAPY_WALLET_SEED: "VN/ikYUHchkZMyjtZcTevtk0D5nLO2Bb" # Register https://selfserve.sovrin.org
  ACAPY_LOG_LEVEL: "info"
  ACAPY_ADMIN: "8001" # http
  ACAPY_INBOUND_TRANSPORT: "8000" # http
  ACAPY_INVITE_MULTI_USE: "true"
  ACAPY_AUTO_ACCEPT_INVITES: "true"
  ACAPY_AUTO_ACCEPT_REQUESTS: "true"
  ACAPY_AUTO_PING_CONNECTION: "true"
  ACAPY_AUTO_VERIFY_PRESENTATION: "true"
  ACAPY_INVITE_LABEL: "Physical Address Credential"
  ACAPY_IMAGE_URL: "https://addrissuer.iamza-sandbox.com/address_logo.png"
  ACAPY_WEBHOOK_URL: "https://addrissuer.iamza-sandbox.com/api/v2/address-issuer"
