---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-issuer
  namespace: address-issuer
  labels:
    app: address-issuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-issuer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: address-issuer
    spec:
      containers:
        - name: address-issuer
          image: 149875424875.dkr.ecr.af-south-1.amazonaws.com/address-issuer:0.2.0
          imagePullPolicy: Always
          ports:
            - name: server-port
              containerPort: 8180
              protocol: TCP
            - name: agnt-adm-port
              containerPort: 8001
              protocol: TCP
            - name: agnt-port
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: address-issuer-configmap
          env:
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addressissuersecret
                  key: emailpw
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addressissuersecret
                  key: emailpw
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: addressissuersecret
                  key: emailusername
            - name: EMAIL_SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: addressissuersecret
                  key: emailsmtpserver
            - name: EMAIL_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: addressissuersecret
                  key: emailsmtpport
